### ISSUE TITLE
Simulation for fluid and computing efficiency

### ISSUE THREAD

**Issue by nuaafhy** [fabricix/MPM-Geomechanics#8]
So sorry to bother you again, I have watched the video about the simulation of surface wave using MPM on youtube. However, I can't find the module about this function in this project. 
Besides, I have tried to simulate the excavation process of a tunnel model with about 70000 particles, and it took about 24 hours to complete 10000 steps, I am not sure whether it's normal or not. 
Hoping to get your reply, many thanks!

**Comment by fabricix** [comment]
Hi, the wave simulation you have see was done with the MPM-PUCRio code. In order to simulate fluids in to the MPM-Geomechanics (this repository) you must to implement some fluid model, like Newtonian fluid, where the volumetric part of the stress tensor can be weak deformable and the shear part of the stress tensor can be strain rate dependent. See for example the elastic model, where the stress integration is done separating the mean and the shear stress components.

**Comment by fabricix** [comment]
The efficiency of the code is still in development, however the current computational time is similar to others code like MPM3D, and MPM-PUCRio. Remember that in an explicit integration time scheme, the critical time step is related to the elastic parameters used in the model.

**Comment by nuaafhy** [comment]
Thank you for your reply. I am wondering whether the MPM-PUCRio is an open-source project and how can I have access to it. Hoping to get your reply, thanks!

**Comment by fabricix** [comment]
The MPM-PUCRio is a code developed during my doctorate. The MPM-Geomechanics is my current MPM project.
Please feel free to collaborate with this project, for example you can create a branch for the Newtonial fluid constitutive model implementation. 

Please, take a look to this implementation for you reference (copied from MPM-PUCRio code):
```
namespace newtonian
{
    double stress_update
    (  
        const patch& pch,   // data structure
        int id,             // identificator
        const Matrix3& F,   // deformation gradient
        Matrix3& S,         // cauchy stress
        Matrix3& dE         // total strain rate
    )
    {
        // material constant
        double mu = pch.mat[id].fluid.viscosity;
        double Kv = pch.mat[id].fluid.bulk;
        
        // aux identity
        Matrix3 I = identity3D();

        // deviatoric part
        Matrix3 sdev  = 2.0*mu*deviatoric(dE);

        // volumetric part
        double devol = trace(dE)*pch.dt;
        double smean = trace(S)/3.0 + Kv*devol;

        // update the cauchy tensor
        S = sdev+I*smean;

        // return
        return det(F);
    }
}

```

This can be easily implemented in the current project in order to model fluids.

**Comment by nuaafhy** [comment]
Okay, thank you very much!
